### ISSUE TITLE
Exporter no longer emitting metrics after eu-central-1 event

### ISSUE THREAD

**Issue by justin-watkinson-sp** [ZipRecruiter/cloudwatching#6]
Hey there!

Wanted to get this on the radar, haven't had a chance to dig, but got a report today from one of our folks that our RDS data was suddenly missing from Prometheus.  Looking back at the timeline, it coincides with when the eu-central-1 event on Tuesday.

Restarting the exporter container restored service, so I guess the takeaway here is to either fail a health check or somehow convince the exporter to exit when it gets stuck.  We run multiple configs in different exporters, so the one impacted containers AWS ES, ELB, ALB, and RDS in the config.  Guessing the APIs were unresponsive and got the exporter into a strange state.

**Comment by frioux** [comment]
It might be good to surface the last time updated and suggest people alert
if that is too far in the past. I can add that; if you find more info
please pass it along. Maybe we somehow are missing some timeouts?

--

**Comment by justin-watkinson-sp** [comment]
Yeah I was just reading up on the absent function which can also be used for this for an alarm (without any extra instrumentation).  If nothing else, that could live as a "README" best practice.

I don't have debug logs on in production and when I looked there was just the start-up message about listening and that's it.

**Comment by justin-watkinson-sp** [comment]
Wanted to give an update.  After staring at some code for a bit, I didn't see any obvious way this could have happened, as that Fatal log on error to refresh should pretty much catch everything, and had we run into that, I should have seen the container bounce several times, but didn't.

After studying the missing AWS metrics with things like the up metric, it became apparent that the application did exit correctly, and upon being spun back up, our Prometheus discovery mechanism (which is file based) timed out, likely due to the AWS event.  The retries were exceeded, so it was likely producing viable metrics, with no Prometheus to know about it, which explains the missing data.

That said, all provenance points to this not being an issue with cloudwatching.  Apologies for the false alarm.

**Comment by frioux** [comment]
Thanks for the in depth report! I really appreciate it

--
